import src as test

# short dna sequence for testing
dna = "AGGCtGCctcTgggCGCATtgaTggTtTATGggCGgtCGAAGAgtCGGACGACTTAACGACTAAAcacacac"

print(test.gcContent(dna))
print()
print(test.countCodon(dna, "CTG"))
print()
print(test.countACG(dna))
print()
test.printCodons(dna)
print()
print(test.findCodon(dna, "CCT"))
print()
print(test.findATG(dna))
print()
test.printReadingFrames(dna)
print()
print(test.firstSSR(dna, "ac"))
print()
print(test.longestSSR(dna, "ac"))
print()
print(test.longestSSRdin(dna))
print()
print(test.complement(dna))
print()
print(test.reverseComplement(dna))
print()
print(test.palindrome(dna))
print(test.palindrome("gaattc"))
print()
print(test.dna2rna(dna))
print()
print(test.transcribe(dna))
print()
print(test.clean("artgtafacckgeaccstgocatgdhcagtf"))
print()
for i in range(20):
    print(test.fix("rhwvn"))
print()
print(test.fixAll("akaba"))
print()
print(test.fixAll("acgt"))
print()
hA = test.readFASTA("NC_001489.fasta")
print(hA)
print()
NC_001489 = test.getFASTA("NC_001489")
print(hA == NC_001489)
print()
print(test.gcContent(NC_001489))
print()
print(test.findseq(NC_001489, "TGTTTTCCAAGATATT"))
print()
print(test.mark("ttgatggagatgcattagaag"))
print()
print(test.proteins("ttg>>>gagcat<<<aagcagaca>>>caccaacag<<<aga"))
print()
inputFile = open('Eco536-500.txt', 'r')
dna = inputFile.read()
inputFile.close()
test.viewer(dna)
